// swift-tools-version:6.2
// Generated by tools/generate-coglint-plugins.mjs. Do not edit by hand.

import PackageDescription

let package = Package(
  name: "CogLintPlugins",
  platforms: [.macOS(.v14)],
  products: [
    .plugin(name: "CogLintBuildToolPlugin", targets: ["CogLintBuildToolPlugin"]),
    .plugin(name: "CogLintCommandPlugin", targets: ["CogLintCommandPlugin"]),
  ],
  targets: [
    .binaryTarget(
      name: "CogLintBinary",
      url: "https://github.com/skeswa/cog/releases/download/0.4.0/CogLintBinary.artifactbundle.zip",
      checksum: "0dbcf7166769ed8e34b9f70597af6fc93b7df422e1ab713dcdce0cff56181877"
    ),
    .plugin(
      name: "CogLintBuildToolPlugin",
      capability: .buildTool(),
      dependencies: ["CogLintBinary"]
    ),
    .plugin(
      name: "CogLintCommandPlugin",
      capability: .command(
        intent: .custom(
          verb: "coglint",
          description: "Check Swift sources against Cog conventions"
        ),
        permissions: []
      ),
      dependencies: ["CogLintBinary"]
    ),
  ]
)
