// swift-tools-version:6.2
// Generated by tools/generate-coglint-plugins.mjs. Do not edit by hand.

import PackageDescription

let package = Package(
  name: "CogLintPlugins",
  platforms: [.macOS(.v14)],
  products: [
    .plugin(name: "CogLintBuildToolPlugin", targets: ["CogLintBuildToolPlugin"]),
    .plugin(name: "CogLintCommandPlugin", targets: ["CogLintCommandPlugin"]),
  ],
  targets: [
    .binaryTarget(
      name: "CogLintBinary",
      url: "https://github.com/skeswa/cog/releases/download/0.7.0/CogLintBinary.artifactbundle.zip",
      checksum: "6bed1e92825ce2681a3bd04ed08de16a1492fb70a01911c8ab4669daa9fb46de"
    ),
    .plugin(
      name: "CogLintBuildToolPlugin",
      capability: .buildTool(),
      dependencies: ["CogLintBinary"]
    ),
    .plugin(
      name: "CogLintCommandPlugin",
      capability: .command(
        intent: .custom(
          verb: "coglint",
          description: "Check Swift sources against Cog conventions"
        ),
        permissions: []
      ),
      dependencies: ["CogLintBinary"]
    ),
  ]
)
